### PR TITLE
Sprint2 integration

### PR DESCRIPTION
**Pull request by vivek-faldu**
Please review the integration branch for sprint2 and merge with master if every thing looks ok

### CODE REVIEW

**Comment by shilpabhat92** [comment]
All functionalities from client and server branches (Sprint 2) merged. 
Major Features merged:
1. movie showtimes
2. search, coming soon
3. Signup
4. Log in

**Comment by jananit2411** [comment]
Tested login, signup, search and movie details page. All functionalities are working fine

**Comment by shaunak11** [comment]
Looking at the commits, all the stories are completed. No conflicts. Great job team. Congrats on completing the sprint.

**Comment by saran1856** [comment]
The team had implemented all the major functionalities that are meant to be do for the sprint. Everything mentioned below is working as team expected:
1) Login.
2) Sign Up.
3) Search functionality.
4) fetching similar movies when user goes to a certain details page.

I agree to merge the pull request.

**Comment by vivek-faldu** [comment]
Closing this request. Code Review Done

**Pull request merged**
